import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { BookData } from './types/types';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function Footer() {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`,
    { cache: 'force-cache' }
  );
  if (!response.ok) {
    return <div>Error in Footer: {response.statusText}</div>;
  }
  const books: BookData[] = await response.json();
  const totalBooks = books.length;
  return (
    <footer>
      <div className='text-sm text-center text-gray-500'>
        © {new Date().getFullYear()} Produced by Cooper
      </div>
      <div className='text-sm text-center text-gray-500'>
        Total Books: {totalBooks}
      </div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className='container mx-auto flex flex-col min-h-screen space-y-4 p-6'>
          <header>
            <Link href={'/'}>
              <h1 className='text-2xl font-bold'>📚 ONEBITE BOOKS</h1>
            </Link>
          </header>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
